from django.db import models


class Foo(models.Model):
    BARS = (
        'accusamus',
        'accusata',
        'ad',
        'adolescens',
        'albucius',
        'alterum',
        'amet',
        'ancillae',
        'animal',
        'cu',
        'cum',
        'debet',
        'detracto',
        'discere',
        'disputando',
        'dissentiet',
        'dolor',
        'duis',
        'duo',
        'ea',
        'efficiantur',
        'ei',
        'erant',
        'est',
        'et',
        'etiam',
        'eu',
        'ex',
        'explicari',
        'fugit',
        'graeci',
        'has',
        'id',
        'idque',
        'in',
        'inimicus',
        'ipsum',
        'legimus',
        'libris',
        'mandamus',
        'mei',
        'modus',
        'nam',
        'nec',
        'no',
        'perfecto',
        'persequeris',
        'pri',
        'principes',
        'purto',
        'recusabo',
        'reprehendunt',
        'sed',
        'signiferumque',
        'similique',
        'sit',
        'soluta',
        'stet',
        'tale',
        'te',
        'ubique',
        'usu',
        'ut',
        'vituperata',
        'vix',
    )
    CHOICES = enumerate(BARS)

    bar = models.IntegerField(choices=CHOICES)
